# Generated by Django 4.2.6 on 2023-11-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_address_alter_order_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phon_number',
            field=models.CharField(max_length=11, verbose_name='تلفن'),
        ),
    ]
