# Generated by Django 4.2.6 on 2023-10-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_comment_is_active_comment_recommend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
