version: '3.10'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000

  db:
    image: postgres:16
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
